Dockerfile
Updates the Dockerfile to specify the entry point as `python -m`. This makes the Dockerfile compatible with the current build args we specified in the infrastructure repo: https://github.com/cowprotocol/infrastructure/blob/f2d440aef6c38729dd2e9983e2e0d48a8720590f/solver-rewards/token-imbalances/index.ts#L52
Also adds `PYTHONBUFFERED=1` to disable buffering of the logs.
=> Update Dockerfile entrypoint

src/config.py, src/daemon.py, src/helper_functions.py, src/sql/select_transactions.sql
This PR is to remove the dependency on the protocol's database for fetching transaction data. 
I have removed select_transactions.sql that was used to make the query to the backend db.
get_tx_hashes_blocks() and get_auction_id() are used to fetch blockchain data (helper functions), and fetch_tx_data() prepares and returns a tuple that constitutes transaction data for our purpose.
=> Remove Backend DB Dependency

src/daemon.py
This PR has a one-line edit:
The start_block in process_transactions() is hardcoded for the current accounting period.
=> Edit start block for current accounting period

.env.sample, README.md, tests/basic_test.py
Updated:
1. basic_test.py to include the fee withdrawal transaction as a test with expected values provided.
2. Updated Readme that provides more high level relevance to what we currently have in this repo.
3. .env.sample edit to make it clear that the last URL (ETHEREUM_NODE_URL) only needs to be provided when running the imbalances_script.py solely, i.e. when testing for a single tx hash.
=> Fee Withdrawal check (pytest), Updated Readme, .env.sample edit

src/coingecko_pricing.py, src/daemon.py
This is a small PR is to include the following changes:
1. WETH price is fixed to equal 1 ETH. So when calling the coingecko price fetching function, token addresses for ETH and now WETH return 1.0, which is the price of each of these tokens in ETH.
2. price_retrievable() checks time elapsed between the latest block and block being processed to make sure it's less than 2 days (currently set to 45 hours), which is coingecko's time frame for fetching 5-minutely data.
=> Coingecko Edits (from discussion)

src/price_providers/dune_pricing.py
This PR catches the [DuneError](https://github.com/duneanalytics/dune-client/blob/775549b7fa9cc4680f78b88d29daddae955b0000/dune_client/models.py#L29) returned by the `dune_client` when it is unable to execute a query. 
Catching and logging this prevents us from receiving alerts about this while still making it easy to find these errors in the logs.
=> Catch dune error

.gitignore, src/price_providers/endpoint_auction_pricing.py
This PR fixes the auction pricing provider to include the barn url endpoint, which is support for staging settlements.
Additionally, the .log file produced on running the daemon was previously added (and is present in main), so this merge will remove the slippage_project.log file.
=> Addressing Issue #38 - Added Staging support

requirements.txt, src/helpers/blockchain_data.py
This PR fixes why the leading 2 characters were missing in the tx_hash logs and db entries.
hexBytes v0.3.0 -> v1.2.1, which is a dependency of the new web3py v7.
=> fix tx hash error

src/fees/compute_fees.py
This PR fixes some minor bug introduced in PR #31 with the conversion of Hex Bytes to strings and vice versa.
=> Hex bug fix

src/transaction_processor.py
This PR will fix the attempted duplicate entry for the slippage_prices table, which was occurring due to not applying a checksum on the fees, and imbalance tokens which resulted in duplicate tokens in the same final slippage dictionary.
=> Fix SQL Error

src/sql/delete_entries_max_block.sql, src/sql/select_max_block.sql
When we merge, entries for the last processed block is deleted and becomes the new start block to avoid missing out on any settlements.
Before this PR, after any merge to main, entries are deleted from `raw_token_imbalances` and `slippage_prices` tables, but not `fees`. This results in an attempted re-write to fees and thus the SQL error in opensearch that the key already exists.
This PR modifies our queries to delete the entries from `fees` too.
=> Fix SQL error in fees

src/constants.py, src/helpers/blockchain_data.py
[These](https://etherscan.io/tx/0x10279eec2aa04d2ea2a09b5d89b166c63d3fda8cfb515973c87a906bcddd6801) types of txs should be ignored.
This PR ignores the `OrderInvalidated` topics and thus such settlements will not be accounted for.
=> Ignore Invalidated Orders

src/daemon.py, src/sql/delete_entries_max_block.sql, src/sql/select_max_block.sql, src/transaction_processor.py
This PR makes things more de-coupled. For instance, since gnosis chain prices are not available currently via price providers, we can now set a configuration in daemon.py by setting `process_prices` to False. Similarly for arbitrum_one. 
Overall, the `process_single_transaction` function is more clear, and entries to the table are done at the end of all computations to ensure that if any issues in either computations arise, then it is added as an unprocessed transaction.
=> Refactoring

src/price_providers/coingecko_pricing.py, src/price_providers/dune_pricing.py, src/price_providers/endpoint_auction_pricing.py, src/price_providers/moralis_pricing.py
As the title suggests, minor changes to specify which APIs haven't been able to provide prices, and due to what reason.
=> Slightly clearer exception handling for prices

src/helpers/database.py, src/sql/schema.sql, src/sql/select_record_exists.sql
There was previously no primary key in the `raw_token_imbalances` table, and instead we had a function called record_exists that would check if (tx_hash, token_address) exists in the table.
Nothing wrong with it, but better to have consistency since the `slippage_prices` and `fees` tables use a primary key, so didn't make sense to have a function just for `raw_token_imbalances`.
The primary key has already been added to `raw_token_imbalances`.
=> Fixed inconsistency in table schema

src/helpers/database.py
Turns out there was a mismatch in the name of the parameter that was passed on to an sql query, that was not properly addressed in PR #53. This PR should do it
=> Fix parameter name passed to sql query

src/fees/compute_fees.py
The code assumes that there is always a "metadata" key in the appdata dictionary. This is not always the case; see e.g, [this](https://explorer.cow.fi/orders/0xc5daf179a664d9032fe9e0c54303cfa51fa838bb508a6e44f0eebe7c7e711521b83899982599174594d2c1abbb3df3325df9f94b66fffa65?tab=overview) order. In such cases, the script produces an error
```
if "partnerFee" in app_data["metadata"].keys():
~~~~~~~~^^^^^^^^^^^^
KeyError: 'metadata'
```
This PR addresses this.
=> Fix metadata issue

src/daemon.py
This PR effectively disables all fee calculations as the backend is pushing protocol/partner fee calculations to prod tomorrow.
As that part of the script has generated a lot of errors due to the various api calls it is doing, this PR proposes to disable it until further notice.
=> Disable fee calculations

src/transaction_processor.py
This PR fixes a bug that made fetching prices depend on fee calculations. Note that we want to make each step of the script independent of one another; e.g., we want to fetch prices for all raw token imbalances even when we don't want to compute fees.
Note that since we need to identify the tokens for which we want to fetch imbalances, the raw token imbalances calculation is still a prerequisite for the price fetching to happen, and this is made explicit.
=> remove dependency on fees when computing prices

src/price_providers/price_feed.py, src/transaction_processor.py
Currently, the script crashes on non-mainnet chains as we don't have available price feeds. This PR fixes the initialization of the price feed object in cases where we don't want to compute prices
=> Initialize empty price feed object on other chains

src/transaction_processor.py
When the daemon restarts, it acts conservatively and deletes the latest entry found in the db, in order to recheck that block. This aims to catch cases where the daemon crashed in the middle of writing in the db. Given that current error handling is not great, this has resulted in cases where the daemon starts crashes and actually starts deleting entries, one by one, ending up in deleting days of data.
This PR proposes to remove this deletion step until we make the daemon very robust, and until we are convinced it is needed. Moreover, it forces the daemon to not look too far back in the past (at most 1 day), and if latest data is older than 1 day, then it ignores the gaps and continues from latest block. In practice, we should not expect downtimes of more than 1 day, so this should be …
=> Remove conservative deletes on restarts

src/price_providers/price_feed.py, src/transaction_processor.py
So far, we have used an ordering of price feeds, in the sense that we query the first API, and if it succeeds, we stop, and only continue with the second price feed if the first one doesn't respond. This PR changes this by forcing the use of all available price feeds/apis always.
=> Use multiple price feeds always

.github/workflows/pull_request.yaml, src/helpers/blockchain_data.py, tests/e2e/test_blockchain_data.py
The PR closes #68.
It also adds a test for the block which broke the script.
~At the moment the test should fail due to a missing node url secret.~
Tests are using a public MEV blocker RPC now and seem to pass. I had to work around the unusual setup of the data fetcher which requires the existence of of a sleep environment variable even though that variable is not needed for fetching blockchain data.
To check that the change actually changes behavior, you can comment out the changed line locally and then run the test via `pytest tests/e2e/test_blockchain_data.py`. It should fail without the change and pass with the change.
=> Fix issue with missing topics

.github/workflows/pull_request.yaml, src/imbalances_script.py, tests/e2e/test_imbalances_script.py
This closes #72.
The test requires an RPC with tracing support.
=> Fix parsing of logs with zero topics

Dockerfile.test_db, Makefile, README.md, database/01_table_creation.sql
This PR adds a setup file for the database and a docker image to create a local database.
The database is set up to have four tables
- A table with settlement transaction hashes and timestamps.
- A table with settlement transaction hashes and token addresses. It should be populated with all tokens traded in a settlement. Together with the first table we have all tokens traded with times when they were traded.
- A table for prices from different sources.
This table structure will be mirrored once per chain.
The database can be set up locally using the commands in the README or using the make file command `make test_db`.
The code does not use this table layout yet. I am planning to add another PR which uses those tables instead of the current tables `raw_token_imbalances`, …
=> Add database setup

src/helpers/database.py, tests/unit/test_database.py
Currently, the code uses local timezone, which can get very confusing. This PR fixes the UTC timezone.
=> Use utc timezone

src/transaction_processor.py
We are spammed with errors about duplicate entries when writing prices in the prices table. this PR silences these errors.
=> Switch error to info until proper restructuring is done

src/helpers/database.py, tests/unit/test_database.py
This PR attempts to fix an issue with writing prices to the database. It _might_ close #82.
Before, it could happen that the same price (i.e. the same token, time stamp, source) was inserted into the prices table. This failed due to violating the primary key constraint. This error (and potentially more?) was silenced in #84.
With this PR, the code first trys to update a value and then inserts it when the update did not succeed.
Alternatively, one could also first try to insert and update if that throws an error.
I added a test for writing a price twice. I was not able to reproduce the error by running the daemon, so that we might need to test some other way.
=> Fix error with writing prices to database
